### ISSUE TITLE
Structural approach for new balcony

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Stephan_Brady_Balcony#1]
HI @stevenuecke, was wondering if you could do a sanity check on the proposed structural approach reflected in the following commit (models)...

https://github.com/OpeningDesign/Stephan_Brady_Balcony/commit/76d244834d136c28fb090bd23691c249f743c19d

Here's the existing conditions: 
https://www.youtube.com/watch?v=7A2QnTbjuOA&feature=youtu.be

When you get a chance, please give me a call to discuss. Thanks Much.

**Comment by stevenuecke** [comment]
I have attached some preliminary mark-ups for you to consider.

Thanks,

Steven Uecke

nTrive

**Comment by stevenuecke** [comment]
Actually, I just uploaded it to the structural folder as ConceptMarkups_01.pdf

**Comment by theoryshaw** [comment]
Thanks Steve for your comments.

Per your following comment...

> THIS PLACES A HUGE AMOUNT OF FORCE INTO THE WALL, AND THEN INTO THE DIAPHRAGM. IT IS LIKELY THAT WE WILL HAVE TO ADD FULL HEIGHT STEEL TUBES IN THE WALL TO TAKE THE LOAD.

Those anchor points are located at existing 16"x12" concrete columns.  Think we would still need full height steel tubes?

Although less desirable, perhaps we could do something like this to distribute the load? 
https://www.dropbox.com/s/o9g1o87rx0gsca2/ScreenHunter_166%20Feb.%2025%2011.01.jpg?dl=0

> EXISTING HEADER? WE WILL PROBABLY NEED TO REINFORCE IT OR ADD A NEW ONE

Header is 18"Hx10"W concrete header.

> 2X10 @ 12" OR 16"

seems excessive.  they're only spanning ~7.5 feet.  Possible to do 2x8's 12" O.C.?

Do you think we can do without the uplift anchor points by using just the weight of the structure alone?

**Comment by stevenuecke** [comment]
These comments were just made as a concept review - I didn't go into too much detail on it yet.
1. Concrete framing: Ok, great- do you have existing drawings for the concrete, so we can see the reinforcement?
2. Floor Joists: Ok, I was going based on the length of the member - I didn't realize it cantilevered that far. 2x8 at 16" is fine.
3. Steel beam: once I looked at the plan view, the span was shorter than I had estimated from the length of the member, so the W12X26 works fine.

**Comment by theoryshaw** [comment]
okay, cool.  Yes, just a high level check is good for now. 

Going to run the concepts by the owner.  If there's sign-off, we'll obviously do more detailed studies. 

No drawing for this building, unfortunately.  Probably have to scan the concrete for reinforcing locations.

She's a pretty beefy structure--old military barracks by the airport.

Will keep you posted. Thx!

**Comment by theoryshaw** [comment]
Hi @stevenuecke 

Made a couple owner requested revisions since the last iteration  --> https://github.com/OpeningDesign/Stephan_Brady_Balcony/commit/9b51dd539c6e1435c7c9d723da14a6c2b4e95d7b

If we can, let's work concurrently on the Revit model via this: http://knowledge.autodesk.com/support/revit-products/downloads/caas/downloads/content/autodesk-a360-collaboration-for-revit-2015.html

I shared the A360 project with you.  You should be getting an invite via email. 

Let me know if you're able to install R4C and if you're able to open the shared model.

Once you do, let's have a followup conversation. 

Thanks!

**Comment by stevenuecke** [comment]
I was able to install this, but I wasn't able to open the shared model - I couldn't see the model through the web browser either, my login says that there is no data in the A360 project.
Also, when I try to access the project in Revit, I get the following:
![image](https://cloud.githubusercontent.com/assets/10428328/6695871/a198cdce-ccb2-11e4-8284-a6fde5f5ae21.png)

Have you been able to make it work?

**Comment by theoryshaw** [comment]
That's unfortunate.  I was under the impression (the wrong one, it seems) that if one party had R4C that they could invite others.  It seems all team members accessing the shared model have to pay $100/month.  Seems like a crazy high price. 

Anyways, we can do this 'old school', if you'd like.  Here's the latest Revit file --> https://github.com/OpeningDesign/Stephan_Brady_Balcony/commit/de610d945319c0300663edf4969cbb90aa02aeac

We can talk tomorrow, if that works for you.

**Comment by stevenuecke** [comment]
Yes, I have synced the Documents, so whenever you want to discuss is fine. Is it time for the full structural design? Also, did you find out whether the owner is concerned at all with the existing structure?

**Comment by theoryshaw** [comment]
Yes, time for full blown design. 

Let's do 10am tomorrow, if that works for you. 
Phone: 302.202.5900
Conference ID: 796-554-157
screensharing: https://join.me/ryanschultz

**Comment by stevenuecke** [comment]
Ok, I'll be on the call

**Comment by theoryshaw** [comment]
@stevenuecke when you get a chance, can you upload that sketch for suggested scan locations.  Thx.

**Comment by stevenuecke** [comment]
Just posted it in the structural folder named as: SB_Balcony_GPRLocations.pdf
