### ISSUE TITLE
Scanning column/beam

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Stephan_Brady_Balcony#2]
@stevenuecke (ping @kraut34)

Apparently scanning of the column/beam will be done today.

They plan on drawing on the column/beam the location of the rebar.

Will it be enough for you to stop by tomorrow sometime and do your assessment?

Thanks.

**Comment by stevenuecke** [comment]
@theoryshaw You can send me the information they come up with - I don't think I need to be on-site for this, right? We need to take the rebar size and placement that they give us and do an analysis on the structure. This will be done in our office, and not on site.

**Comment by theoryshaw** [comment]
Are you in Madison now, or in the near future?

Wasn't intended you to be on site when they are doing it, but only to stop by afterword to extract what you need from the markings on the wall. 

Thanks, Ryan

**Comment by stevenuecke** [comment]
Yes, I'm in Madison now, but I can't extract the information from the wall. They need to provide us with drawings of what they find. If this isn't part of their scope, I'd very highly recommend that it be put into their scope. Without them providing an as-built drawing, there is no liability for them on what they are doing. The owner should have a hard copy that they have certified of what they have found.

**Comment by theoryshaw** [comment]
Talked to Toby, apparently they plan on submitting some documentation.

**Comment by stevenuecke** [comment]
Ok, great. Just send that to me once it comes in, and we'll spend some time on the analysis and get back to you on whether reinforcement is required or not. If we need to come on site, we can do that too. Typically it wouldn't be required unless you wanted us to look at the structure after it is installed to make sure it is per the contract documents.

**Comment by theoryshaw** [comment]
Hi @stevenuecke 

Here's the documentation for the scan of the beam/columns...

https://github.com/OpeningDesign/Stephan_Brady_Balcony/tree/master/Transfer/20150514%20-%20scan%20of%20rebar%20in%20column%20and%20beam

Per usual, possible to get a quick turn around on your design? :)

**Comment by theoryshaw** [comment]
Thanks @andyeck1 for the phone chat.  Yes, next Wednesday will work.

Regarding your question on determining bar size based on sketch.  I talked to Litgen and as i speculated on the phone, they can't determine bar size via a GPR.  So as you mentioned, perhaps we can assume a conservative #3 bar size.

You might have gathered this already, but [here's](https://github.com/OpeningDesign/Stephan_Brady_Balcony/blob/master/Transfer/20150324%20-%20Costing/20150304%20-%20SB_Balcony%20-%20for%20costing.pdf) the latest drawings and [here's](https://github.com/OpeningDesign/Stephan_Brady_Balcony/blob/master/Model/SB_Balcony.rvt) the latest Revit model. 

Andy, are you using https://windows.github.com/ to sync the project folder to your local computer?  If not, talk to @alexcalixto, he'll give you a 101. 

Thanks Much, Ryan

**Comment by kraut34** [comment]
Is this stating that the engineering will be done by next Wednesday?

Toby Krause
Krause Custom Builders
920-285-6490

**Comment by theoryshaw** [comment]
@kraut34 That is correct, per @andyeck1
